import { fileURLToPath } from "node:url";
import type { AgentRuntimeToolName } from "@vioxen/subscription-runtime/core";
import { normalizeBoundedWorkspaceTools } from "./bounded-workspace-tool-policy";

const mcpServerName = "agent_runtime_workspace";

export type CodexWorkspaceToolsProfile = {
  readonly configToml: string;
  readonly developerInstructions: string;
};

export function buildCodexWorkspaceToolsProfile(input: {
  readonly workspaceRoot: string;
  readonly allowedTools: readonly AgentRuntimeToolName[];
  readonly denyProjectInstructions?: boolean;
}): CodexWorkspaceToolsProfile {
  const cliPath = fileURLToPath(
    new URL("../workspace-tools-mcp.js", import.meta.url),
  );
  const enabledTools = normalizeBoundedWorkspaceTools(input.allowedTools);
  const args = [
    cliPath,
    "--workspace-root",
    input.workspaceRoot,
    "--allow",
    enabledTools.join(","),
    ...(input.denyProjectInstructions ? ["--deny-project-instructions"] : []),
  ];
  const configToml = [
    "# Generated by Agent Runtime. Native Codex tools stay disabled.",
    'cli_auth_credentials_store = "file"',
    'approval_policy = "never"',
    'sandbox_mode = "read-only"',
    'web_search = "disabled"',
    "disable_response_storage = true",
    'model_verbosity = "low"',
    ...(input.denyProjectInstructions ? ["project_doc_max_bytes = 0"] : []),
    "",
    "[features]",
    "apps = false",
    "hooks = false",
    "memories = false",
    "multi_agent = false",
    "shell_snapshot = false",
    "shell_tool = false",
    "skill_mcp_dependency_install = false",
    "unified_exec = false",
    "",
    "[tools]",
    "view_image = false",
    "",
    `[projects.${quoteTomlKey(input.workspaceRoot)}]`,
    'trust_level = "untrusted"',
    "",
    "[history]",
    'persistence = "none"',
    "",
    "[otel]",
    'exporter = "none"',
    'metrics_exporter = "none"',
    'trace_exporter = "none"',
    "log_user_prompt = false",
    "",
    `[mcp_servers.${mcpServerName}]`,
    `command = ${tomlString(process.execPath)}`,
    `args = ${tomlStringArray(args)}`,
    `cwd = ${tomlString(input.workspaceRoot)}`,
    `enabled_tools = ${tomlStringArray(enabledTools)}`,
    'default_tools_approval_mode = "approve"',
    "",
    "[shell_environment_policy]",
    'inherit = "none"',
    'include_only = ["PATH", "HOME", "CI", "CODEX_HOME"]',
    "",
  ].join("\n");
  return {
    configToml: `${configToml}\n`,
    developerInstructions: [
      "Use only the agent_runtime_workspace MCP tools exposed for this task.",
      "Native shell, web, delegation, applications, and direct environment tools are unavailable.",
      "All paths must be relative to the provided workspace root.",
    ].join(" "),
  };
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlStringArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function quoteTomlKey(value: string): string {
  return JSON.stringify(value);
}
